### ISSUE TITLE
unalike function generating >0.7 coefficients for low-variability vectors

### ISSUE THREAD

**Issue by RickPack** [raredd/ragree#1]
Unless I am misunderstanding the function, the values returned from homogeneous, or near-homogeneous vectors, are too high. Homogeneous vectors sometimes return even higher values then a near-homogeneous sibling.
`ragree::unalike(factor(c("a","a","a","a","a","b")))`
`0.816`
`ragree::unalike(factor(c("a","a","a","a","a","a")))`
`0.833`

RcmdrPlugin.ISCSS::unalike is returning the values I expect:
`RcmdrPlugin.ISCSS::unalike(c("a","a","a","a","a","a"))`
`0`

Experimentation with other arguments has not solved the problem. For example:
`ragree::unalike(factor(c("a","a","a","a","a","a")), raters=3, subjects=2)`
`0.843`

**Comment by raredd** [comment]
Hi, Rick, I'm not sure of the motivation for `RcmdrPlugin.ISCSS::unalike`, the help file didn't give me any clues, either, but ours was the Kader article which you can find [here](https://ww2.amstat.org/publications/jse/v15n2/kader.html) which does discuss several proposals for this idea.

In particular, we are using the definition for u<sub>2</sub> which is in section 2.5; the examples below from the article and in the docs for `ragree::unalike` correspond to the tables for groups 1-4 in the same article.

```r
l <- list(
  rep(c('a', 'b'), c(7, 3)),
  rep(c('a', 'b'), c(5, 5)),
  rep(c('a', 'b'), c(1, 9)),
  rep(c('a', 'b', 'c'), c(2, 3, 5)),
  rep('a', 10)
)

sapply(l, function(x) 1 - sum(prop.table(table(x)) ^ 2))
# [1] 0.42 0.50 0.18 0.62 0.00

sapply(l, ragree::unalike)
# [1] 0.42 0.50 0.18 0.62 0.00

sapply(l, RcmdrPlugin.ISCSS::unalike)
# [1] 0.4666667 0.5555556 0.2000000 0.6888889 0.0000000
```

Looking over the other definitions from the article, it's not clear to me which one `RcmdrPlugin.ISCSS::unalike` might be. It could be that the formula used by `ragree::unalike` is inappropriate for homogeneous cases, and the value should be 0.

**Comment by raredd** [comment]
I tracked down the discrepancy in how factors were being handled which was causing the difference between passing a factor and character vector (which should not have given different answers). Now I think the function will act [as you expect](https://github.com/raredd/ragree/commit/571dd31ecb9b7545126dd71ce7a58e0ff76e5040):

```r
ragree::unalike(factor(c("a","a","a","a","a","b")))
ragree::unalike(c("a","a","a","a","a","b"))
# [1] 0.2777778

ragree::unalike(factor(c("a","a","a","a","a","a")))
ragree::unalike(c("a","a","a","a","a","a"))
# [1] 0
```

I am still unsure of the `RcmdrPlugin.ISCSS::unalike` function; if you have some insight, please let me know.

Thanks for pointing out the bug in `ragree::unalike`!
